// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type User struct {
	ID        int64
	Email     string
	EmailHash string
	Username  string
	Password  string
}
