// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username,
    password
) VALUES (
    ?, ?
)
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Password)
	return err
}

const findByUsername = `-- name: FindByUsername :one
SELECT id, username, password FROM users WHERE users.username = ?
`

type FindByUsernameRow struct {
	ID       int64
	Username string
	Password string
}

func (q *Queries) FindByUsername(ctx context.Context, username string) (FindByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findByUsername, username)
	var i FindByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
