// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username,
    email,
    email_hash,
    password
) VALUES (
    ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Username  string
	Email     string
	EmailHash string
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.EmailHash,
		arg.Password,
	)
	return err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, username, email, email_hash, password FROM users WHERE users.email_hash = ?
`

type FindByEmailRow struct {
	ID        int64
	Username  string
	Email     string
	EmailHash string
	Password  string
}

func (q *Queries) FindByEmail(ctx context.Context, emailHash string) (FindByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, emailHash)
	var i FindByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailHash,
		&i.Password,
	)
	return i, err
}
